name: Sync MNP Data Archive (Beta)

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository (beta branch)
        uses: actions/checkout@v3
        with:
          ref: beta

      - name: Remove cached submodule reference
        run: |
          git rm --cached mnp-data-archive || true
          git commit -m "Remove cached submodule reference" || echo "Nothing to commit"

      - name: Clone Invader-Zim repo
        run: |
          git clone https://github.com/Invader-Zim/mnp-data-archive.git temp-data
          rm -rf temp-data/.git

      - name: Update mnp-data-archive folder
        run: |
          rm -rf mnp-data-archive
          mkdir -p mnp-data-archive
          cp -r temp-data/* mnp-data-archive/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mnp-data-archive
          git commit -m "Update mnp-data-archive with latest data (beta)" || echo "No changes to commit"
          git push
