name: Sync MNP Data Archive

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout kellanator repo
        uses: actions/checkout@v3
      
      - name: Completely remove any traces of mnp-data-archive
        run: |
          # Force remove the directory and any git references
          rm -rf mnp-data-archive
          rm -rf .git/modules/mnp-data-archive
          
          # Remove from .gitmodules if it exists
          if [ -f .gitmodules ]; then
            sed -i '/\[submodule "mnp-data-archive"\]/,/^\[/ d' .gitmodules
            git add .gitmodules
          fi
          
          # Remove from git index
          git rm --cached -r mnp-data-archive || true
          
          # Clean up any empty files
          if [ -f .gitmodules ] && [ ! -s .gitmodules ]; then
            rm .gitmodules
            git add -u
          fi
      
      - name: Checkout Invader-Zim repo
        uses: actions/checkout@v3
        with:
          repository: Invader-Zim/mnp-data-archive
          path: temp-mnp-data
      
      - name: Create fresh directory and push
        run: |
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create a fresh directory
          mkdir -p mnp-data-archive
          
          # Copy files from temp directory
          cp -r temp-mnp-data/* mnp-data-archive/
          
          # Add, commit, and push
          git add mnp-data-archive
          git commit -m "Complete reset and update of mnp-data-archive" || echo "No changes to commit"
          git push
