name: Sync MNP Data Archive

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Clone Invader-Zim repo
        run: |
          git clone https://github.com/Invader-Zim/mnp-data-archive.git temp-data
          # Immediately remove the .git directory
          rm -rf temp-data/.git
      
      - name: Update mnp-data-archive folder
        run: |
          # Remove existing folder
          rm -rf mnp-data-archive
          
          # Create new folder and copy files (excluding .git)
          mkdir -p mnp-data-archive
          cp -r temp-data/* mnp-data-archive/
      
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add all changes
          git add mnp-data-archive
          
          # Commit and push
          git commit -m "Update mnp-data-archive with latest data from Invader-Zim" || echo "No changes to commit"
          git push
