name: Sync MNP Data Archive

on:
  schedule:
    # Run every day at 6:00 AM UTC
    - cron: '0 6 * * *'
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: ubuntu-latest
    
    # Explicitly set permissions at the job level
    permissions:
      contents: write
    
    steps:
      # Checkout Invader-Zim repo first
      - name: Checkout Invader-Zim repo
        uses: actions/checkout@v3
        with:
          repository: Invader-Zim/mnp-data-archive
          path: invader-zim-repo
      
      # Then checkout your repository with proper token
      - name: Checkout kellanator repo
        uses: actions/checkout@v3
        with:
          repository: Kellan14/kellanator
          path: kellanator-repo
          token: ${{ github.token }}
      
      # Compare and sync changes
      - name: Sync repositories
        run: |
          # Remove existing directory if it exists
          rm -rf kellanator-repo/mnp-data-archive
          
          # Create fresh directory
          mkdir -p kellanator-repo/mnp-data-archive
          
          # Copy all files from Invader-Zim to your repo
          cp -r invader-zim-repo/* kellanator-repo/mnp-data-archive/
          
          # Set up git in your repo
          cd kellanator-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes
          git add mnp-data-archive
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Commit and push changes
            git commit -m "Auto-sync MNP data archive from Invader-Zim"
            git push
            echo "Changes successfully pushed"
          fi
