name: Sync MNP Data Archive

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout kellanator repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for better submodule handling
      
      - name: Remove submodule references if they exist
        run: |
          # Check if .gitmodules exists
          if [ -f .gitmodules ]; then
            # Check if it contains mnp-data-archive
            if grep -q "mnp-data-archive" .gitmodules; then
              echo "Removing mnp-data-archive submodule references"
              # Remove from .gitmodules
              git config -f .gitmodules --remove-section submodule.mnp-data-archive || true
              # Remove from .git/config
              git config --remove-section submodule.mnp-data-archive || true
              # Remove from git index
              git rm --cached mnp-data-archive || true
              # Commit the changes to .gitmodules
              git add .gitmodules
              git commit -m "Remove mnp-data-archive submodule references" || true
            fi
          fi
          
          # Remove the directory if it exists
          rm -rf mnp-data-archive
      
      - name: Checkout Invader-Zim repo
        uses: actions/checkout@v3
        with:
          repository: Invader-Zim/mnp-data-archive
          path: invader-zim-repo
      
      - name: Copy files and push changes
        run: |
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create mnp-data-archive directory
          mkdir -p mnp-data-archive
          
          # Copy files from Invader-Zim repo
          cp -r invader-zim-repo/* mnp-data-archive/
          
          # Add and commit changes
          git add mnp-data-archive
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Commit and push changes
            git commit -m "Auto-sync MNP data archive from Invader-Zim"
            git push
            echo "Changes successfully pushed"
          fi
