name: Sync MNP Data Archive

on:
  schedule:
    # Run every day at 6:00 AM UTC
    - cron: '0 6 * * *'
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout kellanator repo
        uses: actions/checkout@v3
      
      - name: Clone Invader-Zim repo
        run: |
          git clone https://github.com/Invader-Zim/mnp-data-archive.git temp-mnp-data
      
      - name: Update mnp-data-archive folder
        run: |
          # Remove the existing folder
          rm -rf mnp-data-archive
          
          # Create a new folder
          mkdir -p mnp-data-archive
          
          # Copy all files from Invader-Zim's repo
          cp -r temp-mnp-data/* mnp-data-archive/
      
      - name: Commit and push changes
        run: |
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add, commit, and push changes
          git add mnp-data-archive
          git commit -m "Update mnp-data-archive with latest data from Invader-Zim" || echo "No changes to commit"
          git push
